package com.fivedrawdesign.rocketlaunches.contracts;

import com.fivedrawdesign.rocketlaunches.presenters.BasePresenter;
import com.fivedrawdesign.rocketlaunches.views.BaseView;
import com.fivedrawdesign.rocketlaunches.data.model.Launches;

/**
 * This specifies the contract between the view (LaunchListViewFragment) and the presenter
 * (LaunchListPresenter)
 */
public interface LaunchListContract {

    interface View extends BaseView<Presenter> {

        /**
         * Populate the view with the launch data
         * @param result
         */
        void displayLaunches(Launches result);

        /**
         * Displays text in a Snackbar
         * @param message
         */
        void displayMessage(String message);

        /**
         * Displays loading view and hides other views
         */
        void displayLoading();

        /**
         * Displays a view showing no data message and hides other views
         */
        void displayEmpty();

    }

    interface Presenter extends BasePresenter {

        /**
         * Get launches from the Api
         */
        void getLaunches();

        /**
         * Handle errors generated by informing user, logging, sending support email etc.
         * @param t Throwable
         */
        void handleError(Throwable throwable);

    }
}
