package com.fivedrawdesign.rocketlaunches.list_screen;

import com.fivedrawdesign.rocketlaunches.data.entities.Launch;
import com.fivedrawdesign.rocketlaunches.data.source.LaunchesDataSource;
import com.fivedrawdesign.rocketlaunches.utils.BasePresenter;
import com.fivedrawdesign.rocketlaunches.utils.BaseView;

import java.util.List;

/**
 * This specifies the contract between the view (LaunchListViewFragment) and the presenter
 * (LaunchListPresenter)
 */
public interface LaunchListContract {

    interface View extends BaseView<Presenter> {

        /**
         * Populate the view with the launch data
         *
         * @param results
         */
        void displayLaunches(List<Launch> results);

        /**
         * Update the Recyclerview
         */
        void updateDisplay();

        /**
         * Displays text in a Snackbar
         *
         * @param message
         */
        void displayMessage(String message);

        /**
         * Displays loading view and hides other views
         */
        void displayLoading();

        /**
         * Displays a view showing no data message and hides other views
         */
        void displayEmpty();

    }

    interface Presenter extends BasePresenter {

        /**
         * Get launches from the Api
         */
        void getLaunches(LaunchesDataSource.LoadLaunchesCallback callback);

        /**
         * Get launches from the Repository
         */
        List<Launch> getCachedLaunches();

        /**
         * Handle errors generated by informing user, logging, sending support email etc.
         *
         * @param throwable Throwable
         */
        void handleError(Throwable throwable);

    }
}
